### ISSUE TITLE
[QUITING PROJECT] Really someone want continue development?

### ISSUE THREAD

**Issue by dalisoft** [tweenjs/es6-tween#17]
Hi @sole, @mikebolt, @trusktr.

I am see there no interest like original tween.js and community want implement those features tween.js. Then no need for es6-tween. @sole please make someone main dev for this repo or remove (it's your choice, as all of your work its). So if peoples want merge this project to tween.js, i am exit from project. Thanks for anybody, who interested.

I am wait review, reply and things.

**Comment by dalisoft** [comment]
Wow, i am impressed after seen there no interest or nobody want develop the es6-version

**Comment by trusktr** [comment]
I am interested in a modernized tweeting library. At the moment I'm focused
on some WebGL rendering stuff, but at some point I'll be back to handle my
tweenig requirements.

**Comment by dalisoft** [comment]
Okay, when you back you will be amazed as i am introduced some useful things

**Comment by mikebolt** [comment]
I am still interested in working on the es6 version.
