### ISSUE TITLE
Tween instantiation syntax?

### ISSUE THREAD

**Issue by mikebolt** [tweenjs/es6-tween#18]
We should decide on a syntax for tween instantiation. We could use a syntax similar to the current version of tween.js, where options are added to tweens using chainable methods:

    var myTween = new Tween.tween(object).to({a: 1, b: 2}).easing(TWEEN.Easing.Quadratic.In);

The other option is to use an options object:

    var myTween = new Tween.tween(object, {'to': {a: 1, b: 2}, 'easing': TWEEN.Easing.Quadratic.In});

The above two options could both be available at the same time.

Please let me know what you think!

**Comment by dalisoft** [comment]
Looks interesting. I try

**Comment by dalisoft** [comment]
@mikebolt i answered to your question?
