### ISSUE TITLE
Passive versus active source and destination settings

### ISSUE THREAD

**Issue by mikebolt** [tweenjs/es6-tween#19]
There are two ways that a tween can respect the starting values: by only using the starting values when the tween started (passive), or by using the current values from the starting object (active).

I made an example that demonstrates the difference between passive and active in the source and destination objects: https://mikebolt.github.io/discuss/examples/active_tweens.html

I think we should add options for making the tween source-active and/or destination-active. The current default of passive/passive should remain the same.

**Comment by dalisoft** [comment]
I am not understand the feature, please explain bit more. source code too looks logically

**Comment by dalisoft** [comment]
@mikebold maybe you can make PR for this?

**Comment by mikebolt** [comment]
Sure, I can work on this. I haven't looked at the source code for es6-tween yet.

**Comment by dalisoft** [comment]
It's now can be apply via method `setActiveMode()`.
Commit hash https://github.com/tweenjs/es6-tween/commit/056f13ce816b255c46628670e7f6056e068eebab
