### ISSUE TITLE
Publish to npm using a transpiler

### ISSUE THREAD

**Issue by sole** [tweenjs/es6-tween#2]
6to5 sounds like the most serious candidate.

**Comment by sole** [comment]
Since io.js happened, it seems that it's more than possible we might get es6 support in browsers and node before we expected.

Transpilers add a new layer of complexity and I'm starting to dislike them. I was thinking that maybe we shouldn't even bother with them, and write the library entirely in es2015, neé es6.

**Comment by dalisoft** [comment]
Using babel also nice way and already implemented. Even who doesnt know about ES6 can use via Unpkg
