### ISSUE TITLE
Travis tests shows as `unknown` because, not submitted

### ISSUE THREAD

**Issue by dalisoft** [tweenjs/es6-tween#20]
@tweenjs contributors, can you help me with this issue?

**Comment by dalisoft** [comment]
@sole @mikebolt Travis tests still shows *Unknown* as i am not have permission to submit/confirm to Travis CI

**Comment by sole** [comment]
Sorry I hadn't seen this.

I just enabled the repository in Travis. I think it will start running the tests next time there's a push to the repository. Let me know if that works?

**Comment by dalisoft** [comment]
Thanks. I am push when will be new idea for this
