### ISSUE TITLE
The ES6 import was not working properly or not working at all

### ISSUE THREAD

**Issue by dalisoft** [tweenjs/es6-tween#22]

**Comment by ivanherczeg** [comment]
import * as TWEEN from 'es6-tween';

**Comment by dalisoft** [comment]
Thanks. Can you confirm that works this method? Also you have the idea how make import like { Tween, Easing }?

**Comment by dalisoft** [comment]
For me on Rollup+Buble on other app it not works as excepted

**Comment by dalisoft** [comment]
v2.2.6 fixed this issue
