### ISSUE TITLE
Have browser tests on travis - not only npm based

### ISSUE THREAD

**Issue by sole** [tweenjs/es6-tween#3]
Current tests on travis are running on node so we're not actually using `window` or `window.performance`. Travis can run headless browsers, and we should use it to make sure we're not breaking things.

**Comment by dalisoft** [comment]
@sole I don't have access on Travis for this repo. I have made passed all tests on npm

**Comment by sole** [comment]
Sorry @dalisoft, reopening the issue because I don't see travis running tests on the browser :)

What I meant with 'on the browser' is to use something like phantomJS so the tests are run on that environment, using a real `window`object and etc. I am not sure if phantom is the thing people use nowadays, maybe they use Electron? I've no idea :)

**Comment by dalisoft** [comment]
Okay, i am now understand. I try to fix it

**Comment by dalisoft** [comment]
@sole i can't find real demo of this type of demo. Please can you let me know demo?

**Comment by ritwik** [comment]
@dalisoft @sole I think I might be able to get this to work using headless chrome - would that suffice? Is this still something for which community help is needed? If so, I'll take a crack at it if you've not already started :)

**Comment by dalisoft** [comment]
I would be halpful if you do this
