### ISSUE TITLE
Variable "isStarted" is not set properly in core.js

### ISSUE THREAD

**Issue by VictorZhang-1928** [tweenjs/es6-tween#31]
Variable "isStarted" remains "true" after all tweens removed by calling "removeAll" or "remove" in "core.js", so all tweens added after that will never start automatically unless event "visibilitychange" fired.

ps: sorry for my poor english...

**Comment by dalisoft** [comment]
Hi. Thanks for using library. I will test and publish as soon as possible

**Comment by dalisoft** [comment]
[v3.5.2](https://github.com/tweenjs/es6-tween/releases/tag/v3.5.2) release should fix the issue, test, then let me know. [v3.5.2](https://github.com/tweenjs/es6-tween/releases/tag/v3.5.2) is avaiable at [GitHub](https://github.com/tweenjs/es6-tween/releases/tag/v3.5.2), [npm](https://www.npmjs.com/package/es6-tween) and [Yarn](https://yarnpkg.com/en/package/es6-tween), or you can find the distrubtion file links at [here](https://github.com/tweenjs/es6-tween#cdn-hosted-version)

**Comment by dalisoft** [comment]
@VictorZhang-1928 If you think or sure, that bug is fixed, please, close the issue

**Comment by VictorZhang-1928** [comment]
@dalisoft Yes, it's fixed, thanks.

**Comment by dalisoft** [comment]
You're welcome
