### ISSUE TITLE
Consolidation

### ISSUE THREAD

**Issue by trusktr** [tweenjs/es6-tween#33]
Rather than having two repos that are diverging, let's get ideas from here, and make PRs for them in the base tween branch, and let's delete this repo so we can clean up the org.

There's lots of good ideas here @dalisoft 

Then moving forward, what we should do is create new feature branches in the original repo, or make new repos under our own usernames and make pull requests onto the main repo.

**Comment by trusktr** [comment]
List of ideas we'd like to apply to Tween.js:

- [ ] ...

**Comment by dalisoft** [comment]
You right. But i am like to keep this repo live as i am maintining this because there already 31 star. I am always wished become main maintainer of good tweening library. But, maybe i do it if @sole also says this idea

**Comment by dalisoft** [comment]
@trusktr Thanks for idea. I am doing new features, bug-fixes much more than original tween.js, also i am providing [Lite version](https://tweenjs.github.io/es6-tween/Lite.html) of es6-tween, one feature of that faster than [Full version](https://tweenjs.github.io/es6-tween/Tween.html).

As well as @sole, @mikebolt maybe also want to keep tween.js ES5 version keep clean, right?

I am made a [some of plugins](https://www.npmjs.com/browse/keyword/es6-tween), for example, maybe you much commonly use [three.js plugin](https://www.npmjs.com/package/es6tween-plugin-three) as it's makes work easier, i will now focus on examples, as weel as documentation fixes&update.
On each plugin soon will be documentation (can't promise anyway, time is less).
Note, [i am looking for job](https://github.com/tweenjs/es6-tween#adversiting) (you maybe already see ad). After finding the job for my opinions maybe i have less time than now and contributors (best like you @trusktr), PR and Issues are welcomed.
@sole Doesn't have time to mainting as well as @mikebolt time is not much to contribute.
And for original tween.js repo, only much more than i will commit, maybe that makes conflicts (or not?) to keep code clean it's impossible, for that i will update this (es6-tween) repo as more as possible.

And about previus comment, i will want to say, i am always wanted to be contributor of tween.js, [as you see there](https://github.com/tweenjs/tween.js/pulls?q=is%3Apr+author%3Adalisoft+is%3Aclosed), but [only two of them](https://github.com/tweenjs/tween.js/pull/363) are merged, so then i becomed collaraborator of es6-tween repo (big thank you @sole for this and created tween.js 5+ years ago). If who interested some of plugins, they can implement, i describe to bottom clearer (as i can):
- Module of interpolator (string, object, number) is [InterTween](https://www.npmjs.com/package/intertween)
- [Plugins of es6-tween](https://www.npmjs.com/browse/keyword/es6-tween)
- Also can be get via Tree-shaking with
```javascript
import {Timeline, Plugins} from 'es6-tween'
```

It's clear now? Does that helps?
Sorry for bad english, i hope you understand my idea and words.

And big thanks for offer/idea
With best regards,
@dalisoft
with help of
@sole (main maintainer of the tween.js)

**Comment by dalisoft** [comment]
@trusktr I can close this issue?

**Comment by trusktr** [comment]
Yep yep, let's close, just for discussion.

> Also can be get via Tree-shaking with

The PR for rollup on tween.js will add tree shaking.

You have some good ideas here, tween.js could use some!

**Comment by dalisoft** [comment]
@trusktr If @sole @mikebolt and you accept and give me access on tween.js, i will commit to tween.js as possible and make that good

**Comment by trusktr** [comment]
@sole Is the only with the discretion to add collaborators. In the meantime, if you can open pull requests I will gladly help review them so we can get features merged. You have some really good ideas! In particular, it'd be super nice if we can get your `createUi` stuff into a separate repo, it is really really nice and helpful.

**Comment by dalisoft** [comment]
@sole can give we right to admin, then we activer do things, like coverage, code checks via Scrutinizer CI or etc
