### ISSUE TITLE
Tween: Full version [#seek] method isn't working

### ISSUE THREAD

**Issue by dalisoft** [tweenjs/es6-tween#36]
# Issue

### Issue name
Tween: Full version [#seek] method isn't working

### Issue description
Tween: Full version [#seek] method isn't working

### Related
This issue is related to

- [ ] LICENSE
- [ ] README
- [ ] ABOUT COPYRIGHT VIOLATION (be careful before checking this...!)
- [ ] package.json
- [ ] demos/examples
- [ ] core.ts
- [x] Tween.ts
- [ ] lite.ts
- [ ] Easing.ts
- [ ] Interpolation.ts
- [x] Timeline.js

- or provide something else (from es6-tween files...)

### Example
https://codepen.io/dalisoft/pen/boBNaV (remove commented code)

### What you excepted?
Seek the tween

### NOTE
- Please add read code, docs, files, issues, PR list for avoid duplicating existing question, bug or something else...

**Comment by dalisoft** [comment]
I can't figure out why my fix ways not working, help would be nice. @trusktr Maybe we merge this repo to tween.js for more help from community?

**Comment by trusktr** [comment]
> Maybe we merge this repo to tween.js for more help from community?

Yeah, that'd be great because the community is using the main tween.js repo, and focus is there. I would suggest to pick your favorite ideas from here and start adding them there.

The `creatUi` stuff is really cool and useful! I think it'd be nice to have a separate repo just for that, as a standalone package (rather than bundling in the same tween.js package).

**Comment by dalisoft** [comment]
Thank you for best words. I not understand good, but it's mean we start merge?

**Comment by dalisoft** [comment]
Or we make github repo for createUi? Its already on npm. I am working on compatibility for tween.js

**Comment by dalisoft** [comment]
@trusktr Now Tween.js also compatible with `createUi`, [here link](https://unpkg.com/es6tween-tool-createui)

But you should add
```javascript
TWEEN.Tween.prototype.play = TWEEN.Tween.prototype.start;
```
to make play button visible, as it's dynamic by method checking. Make sure call this before
`createUi` instance

**Comment by dalisoft** [comment]
About [#seek] method, it should work partially, always better having partly working than nothing.

**Comment by trusktr** [comment]
> it's mean we start merge?

Yeah, if you can open some new pull requests with changes to Tween.js, then I can review them.

> we make github repo for createUi?

A new repo would be great. I made on here: https://github.com/tweenjs/tween-ui. How do you feel about that name? If you can open pull requests to start merging there, I can start reviewing them. A couple notes:

- perhaps `tweenUi` would be a better name for the function.
- It should reference only `tween.js` (`TWEEN`) so that it is specific for the Tween.js project. (thoughts @mikebolt ?)
- `TWEEN.Tween.prototype.play = TWEEN.Tween.prototype.start;` - this shouldn't be required. But if you think so, can you open a PR on Tween.js so we can discuss it?

> Also don't forget to check Three.js demo. (see directly material.color tweening) how it handles

Which demo? Got a link?

**Comment by trusktr** [comment]
Basically, let's make the `tween-ui` work with the current Tween.js, not considering other libraries in the code. And let's focus on merging your ideas one by one into Tween.js. Then that way many people can enjoy your new features! 👍

**Comment by dalisoft** [comment]
tweenjs.github.io/es6-tween then click Getting Started then scroll to bottom and check Simple demos page

**Comment by dalisoft** [comment]
You have access to create repo on tweenjs? I do not have access

**Comment by dalisoft** [comment]
I think one thing. After these changes to tween.js es6-tween repo will be dead as users can get these things from tween.js?

**Comment by trusktr** [comment]
Yes I do. Sole is busy. The best I can do without her is make a new repo and I can help you merge your code by reviewing PRs.

**Comment by dalisoft** [comment]
I will back in computer after week then i commit to tween ui

**Comment by trusktr** [comment]
Bring your knowledge to Three.js, then eventually when/if @sole is around town she can put you on the team that has access. We can start with PRs for now, to get your ideas in, and as I said I am happy to help review so you can merge. :)

**Comment by dalisoft** [comment]
@trusktr I got full time working (14hour per day), so sorry i have not time to it. @sole if add me, i will do later pr or you can do it yourself

**Comment by trusktr** [comment]
> After these changes to tween.js es6-tween repo will be dead as users can get these things from tween.js?

Forgot to answer that. Yes, users will enjoy your changes in tween.js, and es6-tween will become obsolete.

**Comment by dalisoft** [comment]
then my plugin architecture and lite (faster) becomes unused? The createui is compatible with tween.js. I want to keep es6 tween live and make it popular. Also i think i should move repo to my profile as i can make code coverage, improve code quality and much more by other CI services

**Comment by trusktr** [comment]
> then my plugin architecture and lite (faster) becomes unused?

Unless you would like to prose PRs to implement something like it in Tween.js

> I want to keep es6 tween live and make it popular. Also i think i should move repo to my profile as i can make code coverage, improve code quality and much more by other CI services

True, you could do that.

> The createui is compatible with tween.js.

Interested to put it in the http://github.com/tweens/tween-ui repo?

**Comment by trusktr** [comment]
I meant https://github.com/tweenjs/tween-ui

**Comment by dalisoft** [comment]
I will do that but it should be compatible with es6-tween too. I havent time nw. But you free to imlement that

**Comment by dalisoft** [comment]
I will do but later

**Comment by dalisoft** [comment]
Until now, even, no one of users didn't ask about issue, so if someone need that, please use GSAP/TweenMax (works more than one dev), i'm alone can't fix this
