### ISSUE TITLE
chain is not a function

### ISSUE THREAD

**Issue by joseasv** [tweenjs/es6-tween#40]
Hello there. I just wanted to chain two tweens but the method isn't there. I did what the documentation (http://tweenjs.github.io/es6-tween/docs/tutorial-Basics.html) says in the section "Controlling a tween".

**Comment by dalisoft** [comment]
Sorry i forgot to update docs. Now i havent much time like before. PR are very welcome for fixes

**Comment by dalisoft** [comment]
See #39 i am know issues but i working on police so time very short. Just for reading issues

**Comment by dalisoft** [comment]
Your issue should resolve [4.0.1](https://github.com/tweenjs/es6-tween/releases/tag/v4.0.1)
