### ISSUE TITLE
Can't stop tween when Infinit repeat.

### ISSUE THREAD

**Issue by lizistorm** [tweenjs/es6-tween#41]
Can't stop tween when Infinit repeat. It just ignore when _isFinite is false in Tween.stop/Lite.stop.

But in origin tween.js version there is no _isFinite check in stop function.

**Comment by dalisoft** [comment]
Hi. Thanks for issue. I know this bug, because of createUi i did this trick. But i will introduce major update in 2-3days or max next week. Until it please wait. I am very  want fix, but because of my work i have not time

**Comment by dalisoft** [comment]
Or you can modify code for yourself. If not know TypeScript, after installation with npm, run 'tsc' on directory and you should see src compiled foldrr

**Comment by lizistorm** [comment]
OK. Thanks!

Just remove _isFinite check in stop().

change
`if (!_isPlaying || !_isFinite) {
      return this;
    }`
to
`if (!_isPlaying) {
      return this;
    }`

And maybe _r in stop() should be _reversed. Or it will not go back to start value when reversed.

change
`let atEnd = (_r + 1) % 2 === 1;`
to
`let atEnd = _reversed % 2 === 1;`

**Comment by dalisoft** [comment]
I already fix that in local machine. Just not find time to upload. Thanks for fix again

**Comment by dalisoft** [comment]
Your issue should resolve [4.0.1](https://github.com/tweenjs/es6-tween/releases/tag/v4.0.1)
