### ISSUE TITLE
Import instructions for 'lite' version refer to non-existant file.

### ISSUE THREAD

**Issue by elliottregan** [tweenjs/es6-tween#43]
### Issue description
- I believe that `import { Easing, Interpolation, Tween, autoPlay } from 'es6-tween/src/index.lite'` should end with `.js.`, not `.lite`.

### Related
This issue is related to: README

### What you excepted?
- I expected to be able to paste that line into my code and have access to the lite version of Tween. Instead, I had to change the file extension. 

---

Also, what is the difference between importing { Easing, Tween, autoPlay } from index.js and from es6-tween? I found I had to change `.onUpdate()` to `.on('update', ...)` when importing the library.

**Comment by dalisoft** [comment]
Hi. Thanks for using our library.
But `Lite` was deprecated in v4.x.x

**Comment by dalisoft** [comment]
> Also, what is the difference between importing { Easing, Tween, autoPlay } from index.js and from es6-tween? I found I had to change .onUpdate() to .on('update', ...) when importing the library.

`Lite` version has been optimized, memory effecient and faster until `4.x.x` introducted

**Comment by elliottregan** [comment]
Oh, I see. I didn't realize I was using a different version than what was available over CDN.

Maybe the real bug here is "README isn't updated for the 4.x release"?

**Comment by dalisoft** [comment]
README for 4.x is updated in only GitHub, so please sorry for this. I will fix issue in few days

**Comment by elliottregan** [comment]
No worries! Let me know if you'd like any help.

**Comment by dalisoft** [comment]
I will making something really nice for my users like you (hope you'd like) and should optimize the performance under the hood by some memory cost

**Comment by dalisoft** [comment]
Look at v4.0.2, that should fix docs issue and much some new i few time ago said
