### ISSUE TITLE
Not working in Electron

### ISSUE THREAD

**Issue by Avocher** [tweenjs/es6-tween#45]
# Issue

### Issue name
es6-tween relies on process.hrtime if available, which seems to work unexpectedly(?) in Electron.

### Issue description
Animations doesn't progress in Electron.

### Related
This issue is related to

- [ ] LICENSE
- [ ] README
- [ ] ABOUT COPYRIGHT VIOLATION (be careful before checking this...!)
- [ ] package.json
- [ ] demos/examples
- [x] core.ts
- [ ] Tween.ts
- [ ] lite.ts
- [ ] Easing.ts
- [ ] Interpolation.ts
- [ ] Timeline.js

**Comment by dalisoft** [comment]
Hi @Avocher 
Thanks for using our library
Do you called `TWEEN.autoPlay(true)`?

**Comment by Avocher** [comment]
Yes, I tried both autoPlay and calling update. Setting `process.hrtime = undefined` makes the code work.

**Comment by dalisoft** [comment]
There can you reference some similar issues from `Electron`?
I there can't find way of check `Electron bug`.
PR are welcome and would be helpful

**Comment by dalisoft** [comment]
@Avocher is your issue fixed?

**Comment by Avocher** [comment]
Finally had the time to try it out and it works. Thank you!

**Comment by dalisoft** [comment]
Thank you for catching this bug
