### ISSUE TITLE
Typescript cannot find declaration file (.d.ts) when used via npm

### ISSUE THREAD

**Issue by MarkLodato** [tweenjs/es6-tween#46]
# Issue

### Issue name
Typescript cannot find declaration file (.d.ts) when used via npm

### Issue description
When one tries to import es6-tween in TypeScript, they get:

```
ERROR in [at-loader] ./lib/graphics.ts:7:24 
    TS7016: Could not find a declaration file for module 'es6-tween'. '[...]/node_modules/es6-tween/full/Tween.js' implicitly has an 'any' type.
  Try `npm install @types/es6-tween` if it exists or add a new declaration (.d.ts) file containing `declare module 'es6-tween';`
```

### Related
This issue is related to

- [X] package.json

### What you excepted?
To fix, you simply need to add a `"types"` field in package.json. See http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html.

I'll send a pull request.

**Comment by Arlodotexe** [comment]
I'm seeing this issue again. Looks like there used to be TS definitions [here](https://github.com/tweenjs/es6-tween/tree/70098fb4fa9f34622cdad5b3c8a9df88e4abe1e3/ts), but they no longer exist.

**Comment by dalisoft** [comment]
PR is welcome =)
