### ISSUE TITLE
Is there some kind of 'complete' event or onComplete method for es6-tween?

### ISSUE THREAD

**Issue by shongololo** [tweenjs/es6-tween#49]
# Issue

### Issue name
Is there some kind of 'complete' event or onComplete method for es6-tween?

### Issue description
I can't seem to find anything in the documentation and attempts at using a `.on('complete...)` method don't seem to work.

### Related
This issue is related to
- [x] demos/examples
- [x] core.ts
- [x] Tween.ts

### Example
I'm trying to do something like this:
```
new Tween({ opacity: 0.85})
            .to({ opacity: 1 }, 500)
            .easing(Easing.Quadratic.InOut)
            .reverse(true)
            .on('update', ({ opacity }) => {
              do something...
            })
            .on('complete', () => {
              do something once tween completes
            })
```

**Comment by dalisoft** [comment]
Hi @shongololo 

[Here online demo](https://codepen.io/dalisoft/pen/WdbdRz) i'm pasted your code and fixed these:
1. Set `autoPlay(true)` for automatic running tweens loop
2. Call `.start()` for running tween

Node:
`.reverse()` may not work as excepted, i haven't much time to fix these issues for now
