### ISSUE TITLE
My tween only has a precision of four decimal points.

### ISSUE THREAD

**Issue by donaldr** [tweenjs/es6-tween#58]
I have a tween going from 2 to 1.98 over twenty seconds. I log my tween and it only goes to four decimal places. I'm not rounding it anywhere in my code.

**Comment by moroine** [comment]
Hello,

I just try to reproduce, and on my side, it's not the case.

See https://codepen.io/bilouwan/pen/QJmQdW?editors=1111 

Could you add an example?

**Comment by dalisoft** [comment]
Hello @donaldr. 
Is the #56 not fixed your problem? If fixed, please close issue

**Comment by dalisoft** [comment]
@donaldr Please try `v5.3.2`, i released new version, it should be fixed. Thank you for reporting bug

**Comment by dalisoft** [comment]
Now the decimals limit not 4, an approx 6-7, i think it's enough for smooth tweening and 32-bit integer limit also was fixed. If still issue persist, please reopen issue or create another one
