### ISSUE TITLE
Tween only run first time since 5.4.x

### ISSUE THREAD

**Issue by homerjam** [tweenjs/es6-tween#65]
Repro url: https://codesandbox.io/embed/24w5k8v3zn

**Describe the bug**
Since version 5.4.x tweens seem to only play first time around. For example I have the following code which creates and runs a new tween programatically, this works as expected in 5.3.x but only works the first time in 5.4.x.

I see there were some changes that mention timeline - could this be something to do with it?

Thanks

```
    watch() {
      new Tween({ offset: this.alternate ? 0 : 1 })
        .to({ offset: this.alternate ? 1 : 0 }, this.speed)
        .easing({
          offset: Easing.Quadratic.InOut,
        })
        .on('update', this.render)
        .start();
    },
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dalisoft** [comment]
Hello and thanks for using this library. Please, can you create simple codepen snippet for i am being able to see what happens and fixing issue

**Comment by homerjam** [comment]
https://codesandbox.io/embed/24w5k8v3zn

**Comment by dalisoft** [comment]
Thanks @homerjam. I got what going wrong, i soon fix.
There you can watch minimal pen of what's wrong: https://jsbin.com/luyizar/edit?js,console

**Comment by dalisoft** [comment]
@homerjam Can you try [v5.4.2](https://github.com/tweenjs/es6-tween/releases/tag/v5.4.2)? It is fixed for your app?

_if yes, please close issue_

**Comment by homerjam** [comment]
Yes it works! (tested with 5.4.3) Thanks!
