### ISSUE TITLE
Do not publish .git subdirectory to npm registry

### ISSUE THREAD

**Issue by agavrilov** [tweenjs/es6-tween#66]
**Describe the bug**
'.git' subdirectory is published to NPM registry in version 5.4.2. It contains hooks/README.sample. The presence of '.git' subdirectory triggers a bug in NPM which prevents the installation of _other_ packages: https://github.com/npm/npm/issues/17475

**Expected behavior**
'.git' subdirectory should not be a part of published version

**Comment by dalisoft** [comment]
Hi and thanks to reporting issue. How it published i not sure, looks bug on my notebook. I'll publish a new one, thanks again :)

**Comment by dalisoft** [comment]
Thanks a lot, fixed!
