### ISSUE TITLE
Visual jump after pause

### ISSUE THREAD

**Issue by pfrlv** [tweenjs/es6-tween#67]
Hello, after `this.tween.pause()` in this case:

```javascript
this.node.addEventListener('mouseenter', this.pause)
this.node.addEventListener('mouseleave', this.play)

this.tween = new window.TWEEN.Tween({ x: 0 })
  .to({ x: this.contentWidth * -1 }, random(4, 8) * 1000)
  .easing(window.TWEEN.Easing.Quintic.InOut)
  .on('update', (v) => {
    this.wrapper.style.setProperty('transform', 'translate3d(' + v.x + 'px, 0, 0)')
  })
  .repeat(Infinity)
```
I have a visual backward or forward jump for 1/3px on `this.wrapper`. I work with about 20 wrappers.

 - OS: MacOs
 - Browser chrome
 - Version 73.0.3683.103 (Official Build) (64-bit)

**Comment by dalisoft** [comment]
Hello and thanks for reporting. Can you create specific demo on Codepen or something similar service such as jsbin, jsfiddle?

**Comment by pfrlv** [comment]
> Hello and thanks for reporting. Can you create specific demo on Codepen or something similar service such as jsbin, jsfiddle?

So i did https://jsfiddle.net/qkg5L7ue/28/

**Comment by dalisoft** [comment]
Please can you check this [fiddle](https://jsfiddle.net/3oxL7gnd/)? It is ok now?

**Comment by pfrlv** [comment]
Давлат, привет! Понял, что ты русский. В твоем фидле тоже дергается. Самое странное, что в версиях ниже 4.2.0 пауза работает отлично.

**Comment by dalisoft** [comment]
@pfrlv Привет. Да, знаю русский! Я проверю что не так, как только найду время, хорошо? Сейчас я занять работой, ну точно буду проверить

**Comment by pfrlv** [comment]
@dalisoft спаисбо )

**Comment by dalisoft** [comment]
@pfrlv Теперь можете проверить этот [фиддл](https://jsfiddle.net/dalisoft/cmpnzqso/2/)?

**Comment by pfrlv** [comment]
@dalisoft отлично! В чем причина?

**Comment by dalisoft** [comment]
@pfrlv проблема был в код которые пытается нормализовать времени если внутри обновление что-то сложное (которые много время займёт) происходить

**Comment by dalisoft** [comment]
Если проблема решена, можете закрыть исю?

**Comment by pfrlv** [comment]
Понял, спасибо! Закрываем

**Comment by dalisoft** [comment]
И вам спасибо за репорт бага. Хорошего вечера
