### ISSUE TITLE
Missing file for using as bundled/Tween.js

### ISSUE THREAD

**Issue by seIncorp** [tweenjs/es6-tween#70]
**Describe the bug**
Under installation first link to file is not working

**To Reproduce**
Click on this url https://raw.githubusercontent.com/tweenjs/es6-tween/master/ts/Tween.ts and you will get: 404: Not Found.

**Comment by dalisoft** [comment]
Why do you want get TS file? The project fully rewritten to JS because of performance, do you see releases changelog?

**Comment by dalisoft** [comment]
Auh, did not noticed. Can you create PR for it too?

**Comment by seIncorp** [comment]
Done.

**Comment by dalisoft** [comment]
Nice. Thanks.
