### ISSUE TITLE
New demo/example.

### ISSUE THREAD

**Issue by seIncorp** [tweenjs/es6-tween#73]
You can use this example for promoting your project.

In the case, if you use this example, please use the reference where you got this example.

Link to this example:
https://github.com/seIncorp/Examples/tree/master/p5JS/Tween/Example%202

**Comment by dalisoft** [comment]
Hello and thanks a lot for demo. But i cant use demo, because
- demo should be available for everyone (host on codepen for example)
- i not promote this project, who loves performance and flexibility, will find this project
- you can make PR with including demo in examples folder
