### ISSUE TITLE
Implementing tween#get and Famous Transitionable-like constructor

### ISSUE THREAD

**Issue by dalisoft** [tweenjs/es6-tween#8]
See https://github.com/tweenjs/discuss/issues/1#issuecomment-282525375

**Comment by dalisoft** [comment]
Fixed with [last commit](https://github.com/tweenjs/es6-tween/commit/4eb0f1c0155e176bed3e865db695cb475f55963e)

**Comment by trusktr** [comment]
Cool, looking forward to API like this!
