### ISSUE TITLE
在微信小游戏中缓动效果不生效

### ISSUE THREAD

**Issue by JustClear** [tweenjs/es6-tween#81]
`es6-tween` is not working in wechat minigame

复现步骤
1. 正常调用 API
2. 在微信小游戏中执行

**Expected behavior**
动画能正常播放

**Comment by dalisoft** [comment]
Hi @JustClear 

Sorry, i don't know Chinese. Google Translator also did not translated correctly.
But recently i changed README and added NOTE related to project maintainity.

https://github.com/tweenjs/es6-tween#note

Thanks for interest.

Regards, Dav
