### ISSUE TITLE
chain() with Tween only, not group

### ISSUE THREAD

**Issue by anat** [tweenjs/es6-tween#84]
It is probably a feature request but in the original tweenjs, it is possible to chain not only groups but also tweens.

Maybe I'm wrong, I'll investigate more to find out.

I think that in the original one they create a group when you need it, I'll have to refactor my code to make my code to work with a bit more code that could have been avoided.

**Comment by dalisoft** [comment]
I think you made issue in wrong repo as you want original tweenjs. 
Go to https://github.com/tweenjs/tween.js and create issue. 

This project isn’t maintaining anymore and no issues will be processed
